### ISSUE TITLE
Some method to handle insecure-registries and other docker-daemon settings

### ISSUE THREAD

**Issue by mriedmann** [cloudflightio/dockerinwsl#12]
For some use-cases it is necessary to set insecure-registries (registries that provide no or untrusted certificates). There was a possibility in Docker Desktop to set these setting. We should provide a way to handle this somehow.

**Comment by daviian** [comment]
I believe one issue at the moment is that every change you apply inside of the docker wsl instance gets removed with a future update.

**Comment by mriedmann** [comment]
see https://github.com/cloudflightio/dockerinwsl#how-to-configure
