### ISSUE TITLE
No connectivity between WSL2 and Windows Host

### ISSUE THREAD

**Issue by mriedmann** [cloudflightio/dockerinwsl#15]
Some (if not all) people can't connect to services running on the windows host. At this point it is not 100% clear if this is intentional. It is very like due to a missing firefall rule.
For now you can workaround this by disabling the Firewall on the WSL Interface. This is a bit risky so be careful with that.

* Disable (fix): `@("domain","public","private") | %{ Set-NetFirewallProfile -Name $_ -DisabledInterfaceAliases "vEthernet (WSL)" }`
* Enable (unfix): `@("domain","public","private") | %{ Set-NetFirewallProfile -Name $_ -DisabledInterfaceAliases @() }`

**Comment by mriedmann** [comment]
To ease some pain we can add `New-NetFirewallRule -DisplayName "WSL" -Direction Inbound  -InterfaceAlias "vEthernet (WSL)"  -Action Allow` to the installation so non-blocked applications can be accessed from WSL. The problem is, that most applications will be protected by the Windows Firewall due to a Block Rule that targets directly on the binary. These rules would have to be removed manually, making these Apps reachable from the outside. That could pose a security risk.

Disabling the firewall on the WSL interface has less security implication on other parts but also makes room for attacks from compromised docker-containers or wsl-distros (not only ours). 

Quite satisfying, maybe someone else has an idea?

**Comment by mriedmann** [comment]
Just for the record, this might actually be also solved with this: #13

**Comment by rala72** [comment]
To fix the connection issue with IntelliJ I changed the IP address to `0.0.0.0` here:
https://github.com/cloudflightio/dockerinwsl/blob/2fd8670d5631f055c2f60ee2eeb1eba1b8cdf925/msi/docker.bat#L16

**Comment by mriedmann** [comment]
Interesting. Have you still used 127.0.0.1 as remote adress in IntelliJ or have you changed it to something else? In theory this should not make a difference (because the actual connection is done via wsl.exe and not the "normal" network-stack in hyper-v). But I am also still figuring out how everything works together exactly.

**Comment by rala72** [comment]
I'm using `localhost` in Intellij which resolves to `0:0:0:0:0:0` according to service window.

**Comment by mriedmann** [comment]
Currently there are more and more reports that suggest a problem here. Because #17 will stir up a lot of things I will focus on that for now and continue to investigate this issue after that if it is not solved by VPNKit and the switch to Ubuntu.

Nevertheless, if someone needs help with this kind of issue, feel free to post here and add some information.

**Comment by mriedmann** [comment]
The newest prerelease should fix this (https://github.com/cloudflightio/dockerinwsl/releases/tag/v1.2.83). Will close this after final release.

**Comment by mriedmann** [comment]
should be solved with 1.2.x. Please comment here if you experience these problems also with the latest version.
