### ISSUE TITLE
Unable to connect to docker-daemon with IntelliJ

### ISSUE THREAD

**Issue by mriedmann** [cloudflightio/dockerinwsl#35]
There is a problem that WSL for whatever reason binds the daemon port (2375) only to ::1 (lo ipv6) and not to 127.0.0.1 (lo ipv4). Normally this is no problem, especially if you define your daemon url as `tcp://localhost:2375` but there are 2 possibilities where this might cause issues (possible error-message `java.net.ConnectException: Failed to connect to localhost/127.0.0.1:2375`).

1. You have set `-Djava.net.preferIPv4Stack=true` as startup parameter to intellij
2. You have removed the `::1` part of localhost inside the hosts-file (`C:\Windows\System32\driver\etc\hosts`)

Both scenarios force your idea to use ipv4, which is not available.

I will try to figure out why wsl2 is only binding to ipv6. If someone has more information on this topic please share it here.

**Comment by mriedmann** [comment]
We also encountered the opposite effect: No IPv6 only IPv4 binding but timeout because IPv6 is preferred and the fallback is not working for some reason ... please report here if you are experience anything in this direction. This "bug" is quite elusive.

**Comment by mriedmann** [comment]
Encountered something similar once again. Now with `ng serve`. Hotfixed it with `ng serve --host 127.0.0.1 --disable-host-check`.

 Currently there is no IPv6 connection from WSL (=Docker) to Windows. Maybe #26 can help here.

**Comment by d-eder** [comment]
I had a similar issue with TestContainers. The startup failed due to the same exception (`java.net.ConnectException: Failed to connect to localhost/127.0.0.1:2375`).
After changing the env variable `DOCKER_HOST` to `tcp://[::1]:2375` it worked.

**Comment by mriedmann** [comment]
should be fixed in 1.3.120.220809
