### ISSUE TITLE
wsl --shutdown $DISTRONAME, Distroname no effect

### ISSUE THREAD

**Issue by Duncat** [cloudflightio/dockerinwsl#36]
https://github.com/cloudflightio/dockerinwsl/blob/d2a5d4898086c4b4bf80cd05d3dc70a42703f883/msi/scripts/docker-wsl-control.ps1#L54

$DISTRONAME parameter does not have any effect as wsl --shutdown kills all distros

**Comment by mriedmann** [comment]
Thank you very much for pointing this out. The right command should be `wsl -t $DISTRONAME`. I will fix that as fast as possible.
