### ISSUE TITLE
wsl shell not working from GitBash

### ISSUE THREAD

**Issue by mriedmann** [cloudflightio/dockerinwsl#38]
Running `wsl -d clf_dockerinwsl` from GitBash leads to a "hanging" screen but no bash/shell. This should be investigated. Maybe it can be fixed on our side.

**Comment by 7DataBits** [comment]
Problem is that windows gitbash does not provide a TTY shell for commands by default
You can fix this by using the builtin wrapper to execute to command with a TTY shell:
`$ winpty wsl -d clf_dockerinwsl`
