### ISSUE TITLE
Docker is not detected anymore with TestContainers 1.17.2 or later

### ISSUE THREAD

**Issue by klu2** [cloudflightio/dockerinwsl#46]
Since [1.17.2](https://github.com/testcontainers/testcontainers-java/releases/tag/1.17.2) of TestContainers, Docker is not being detected anymore (i.e. when using PlayTika TestContainers)

A possible reason could be https://github.com/testcontainers/testcontainers-java/pull/5357

Interestingly, we had a dockerInWsl version from before-winget-times, that was compatible even with the changes in 1.17.2, but the latest version on winget isn't.

**Comment by mriedmann** [comment]
Can reproduce. Thx. Will investigate.

test-jars:
[testcontainers-starter-server-1.17.1.zip](https://github.com/cloudflightio/dockerinwsl/files/9290109/testcontainers-starter-server-1.17.1.zip)
[testcontainers-starter-server-1.17.3.zip](https://github.com/cloudflightio/dockerinwsl/files/9290112/testcontainers-starter-server-1.17.3.zip)

**Comment by mriedmann** [comment]
Workaround: `$env:DOCKER_HOST="tcp://[::1]:2375"`

Related to #35 

Fix upcomming.
