### ISSUE TITLE
Support Compose V2

### ISSUE THREAD

**Issue by beinzi** [cloudflightio/dockerinwsl#50]
It would be nice to support the new [docker compose](https://docs.docker.com/compose/reference/) command, e.g., to be used by the [Docker](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker) VS Code plugin.

> Compose V2 integrates compose functions into the Docker platform, continuing to support most of the previous docker-compose features and flags. You can run Compose V2 by replacing the hyphen (-) with a space, using docker compose, instead of docker-compose.

**Comment by jkogler-cloudflight** [comment]
It should be possible to use Compose V2 with VS Code. However it's necessary to set the `docker-compose` path in the VS Code settings.

1. Open the settings: <kbd>Ctrl</kbd> + <kbd>,</kbd>
2. Search for `docker compose path`
3. Enter `docker compose` (with a space instead of a dash).

**Comment by beinzi** [comment]
@jkogler-cloudflight, thanx for the hint!

The default of the latest VS Code plugin seems to be the V2 command. But it can be done the other way round and set `docker-compose` as command in the settings. V2 is not supported yet and will fail.

**Comment by jkogler-cloudflight** [comment]
Clarification: 
Compose V2 is not yet supported by `dockerinwsl`. VS Code tries to use V2 automatically, and with the settings - as described in my previous comment - you can use V1 in VS Code.
