### ISSUE TITLE
Mirror not set automatically

### ISSUE THREAD

**Issue by xVinci6** [cloudflightio/dockerinwsl#54]
The procedure described in our internal document - https://confluence.cloudflight.io/pages/viewpage.action?pageId=146608632 - is cumbersome. The WSL distro has no text editing tools installed - Please configure our internal mirror automatically.

**Comment by mriedmann** [comment]
Will not happen. This project is actively generalized for everyone to use not only Cloudflight (as it is a public repository).

We are currently working on a "plugin" system. Maybe we can make the process easier with it.

(You know that you can edit the daemon.json file from windows right? See https://github.com/cloudflightio/dockerinwsl#how-to-configure)
