### ISSUE TITLE
Install fails with code 1603

### ISSUE THREAD

**Issue by NTrixner** [cloudflightio/dockerinwsl#55]
When trying to install on my private PC, the install fails with exit code: 1603

This is the log file:
[WinGet-Cloudflight.DockerInWSL.1.3.119.220810-2022-12-29-10-00-27.727.log.txt](https://github.com/cloudflightio/dockerinwsl/files/10318622/WinGet-Cloudflight.DockerInWSL.1.3.119.220810-2022-12-29-10-00-27.727.log.txt)

I am running powershell as an administrator

**Comment by mriedmann** [comment]
`Unable to import WSL distro from 'C:\Program Files\DockerInWSL\image.tar' to  'C:\Users\Krampus\AppData\Local\DockerInWSL\wsl'` might hint to a full disk or some other problem with wsl. Anything interesting in `C:\Users\Krampus\AppData\Local\Temp\dockerinwsl-install.log`?

Can you also please provide some more info on your system? Win Version, Wsl Version, etc.

Thx

**Comment by NTrixner** [comment]
[WinGet-Cloudflight.DockerInWSL.1.3.119.220810-2023-01-10-20-19-28.656.log](https://github.com/cloudflightio/dockerinwsl/files/10387017/WinGet-Cloudflight.DockerInWSL.1.3.119.220810-2023-01-10-20-19-28.656.log)

The disk is actually still half empty - 550GB free of 930.

The system is Win 10 Pro, Versin 22H2, on a Ryzen 9 3900X 12-Core 3,8 GHz, 64 GB RAM with a 1080.
It's on an MSI X570-A PRO
I tried to activate SVM for Docker for windows, but that always caused a bluescreen, which is why I'm trying to use WSL.

For WSL:
```
PS C:\WINDOWS\system32> wsl --version
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.2364
```

**Comment by mriedmann** [comment]
K thx ... Can you please also provide this file: C:\Users\Krampus\AppData\Local\Temp\dockerinwsl-install.log

**Comment by NTrixner** [comment]
[dockerinwsl-install.log](https://github.com/cloudflightio/dockerinwsl/files/10395705/dockerinwsl-install.log)
Ah sorry, here you go

**Comment by mriedmann** [comment]
Ok not that helpful either xD

Is any other WSL Distro installed and running without problems? If not, please try to install the latest ubuntu in wsl (`wsl --install`) just to make sure it is working correctly.

**Comment by NTrixner** [comment]
Sorry for not answering yet, just installed a new gpu and now I can't even start windows. I'll answer once I can get back into it.

**Comment by NTrixner** [comment]
I completely forgot to answer here:
there was a multitude of issues with my setup, ranging from SVM not being enabled in the bios, to my package store being corrupted. Took me a while, but I was able to fix it and now the installation worked. Thanks!
