### ISSUE TITLE
Add a docker and docker-compose wrapper script to PATH

### ISSUE THREAD

**Issue by mriedmann** [cloudflightio/dockerinwsl#6]
To make using this package easier it might be a good idea to provide a set of cli wrapper scripts. These could just wrap `wsl -d <distro> docker` and provide a docker-like experience on powershell and cmd.

Please emoji-vote on that feature if you would use it.

**Comment by NoUsername** [comment]
An alternative would be to either automatically run or put a hint in the documentation to:

```
choco install docker-cli
choco install docker-compose
```

to get the most common command line tools installed. would then also be discoverable by other tools that maybe actually search for a "docker" binary on the path 🤷
