### ISSUE TITLE
Windows Script files link to the wrong script

### ISSUE THREAD

**Issue by Rsilnav** [cloudflightio/dockerinwsl#75]
When installing DockerInWSL (1.4.146.230220), the scripts generated in `C:\Users\USER\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\DockerInWSL` are actually referencing `docker.bat` instead of `docker-wsl.bat`, hence not allowing for a correct docker startup since it is calling the wrong command.

**Comment by mriedmann** [comment]
Thx for the report. Will be fixed with 1.5.
