### ISSUE TITLE
Docker not starting inside WSL distro upon reboot / startup

### ISSUE THREAD

**Issue by xVinci6** [cloudflightio/dockerinwsl#8]
When shutting down / starting, rebooting the machine or re-logging into windows the docker service seems to not start automatically. Only after calling docker.bat start clf_dockerinwsl the daemon is running as expected.

**Comment by mriedmann** [comment]
Can you please check the `shell:startup` folder (usually `C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`). There should be a link to the bat file with the start arguments inside. This should lead to an "autostart".

**Comment by mriedmann** [comment]
it seems that this is a quite complex race-condition problem. I will add some basic logging to investigate this further. Also maybe #6 could help. We could add a "start on demand" function to the wrapper.

**Comment by chuber50** [comment]
> Can you please check the `shell:startup` folder (usually `C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`). There should be a link to the bat file with the start arguments inside. This should lead to an "autostart".

the link + file are there in my case.
Maybe we have to re-introduce the startup delay?

**Comment by mriedmann** [comment]
The newest Version (1.1.47) is logging some startup-information to %LOCALAPPDATA%/Temp/dockerinwsl.log ... Maybe we can gather some information using these logs.

**Comment by mriedmann** [comment]
should be solved with 1.2.x. Please comment here if you experience these problems also with the latest version.
