### ISSUE TITLE
Docker deamon is not running inside WSL

### ISSUE THREAD

**Issue by Pystronic** [cloudflightio/dockerinwsl#85]
DockerInWSL worked after the initial install, even though it had some problems on Windows 11.
I restarted the system since then and tried to use docker again. However, the docker deamon is not running inside the vm.
Restarting the deamon using *service* also does not work, because of missing privileges.

It seems like the start-docker command is never actually starting the docker service and instead just checks if the the wsl vm is running.

> PS C:\Users\<>\IdeaProjects\...> docker-wsl restart-all
[04.17.23 08:11:30] Stopping ...
[04.17.23 08:11:34] docker seems to be stopped already. /run/supervisord.pid not found
[04.17.23 08:11:34] Shutting down WSL ...
[04.17.23 08:11:34] shutdown completed!
[04.17.23 08:11:36] Starting ...
[04.17.23 08:11:40] ... started!
Der Vorgang wurde erfolgreich beendet.
>
>PS C:\Users\<>\IdeaProjects\...> wsl service docker status
> * Docker is not running

**Comment by mriedmann** [comment]
Can you please post your installed version? Thx

Also: The status command you are using will not work with dockerinwsl pls use `docker-wsl status`.

You can also run `docker-wsl-test` to check the system and post the output here.

**Comment by Pystronic** [comment]
I removed and reinstalled DockerInWSL and it is now working again. I will still post my system information in case this comes up again.

> C:\Users\<>>winget show DockerInWSL
> Gefunden DockerInWSL [Cloudflight.DockerInWSL]
> Version: 1.4.148.230412
> Herausgeber: Cloudflight GmbH
> Herausgeber-URL: https://cloudflight.io
> Herausgeber-Support-URL: https://github.com/cloudflightio/dockerinwsl
> Autor: Cloudflight GmbH
> Moniker: dockerinwsl
> Beschreibung: Using WSL2 to run a docker on windows (using official dind alpine image)
> Startseite: https://github.com/cloudflightio/dockerinwsl
> Lizenz: Apache2
> Copyright: Copyright (c) Cloudflight GmbH
> Markierungen:
>   docker
>   wsl2
> Installationsprogramm:
>   Installertyp: wix
>   Installer-Gebietsschema: en-US
>   Installer-URL: https://github.com/cloudflightio/dockerinwsl/releases/download/v1.4.148/DockerInWSL_1.4.148.230412.msi
>   Sha256-Installer: 41c19c788d6355cb7111a300ba5becbae1715544f6357620c198da62075ac233

> C:\Users\<>>docker-wsl-test                                                                                       [OK  ] wsl exists (C:\Windows\system32\wsl.exe)                                                                         [OK  ] docker exists (C:\Users\<>\AppData\Local\DockerInWSL\scripts\docker.bat)                                   [OK  ] docker-wsl exists (C:\Users\<>\AppData\Local\DockerInWSL\scripts\docker-wsl.bat)                           [OK  ] 'wsl -l' succeeded                                                                                               [OK  ] localhost:2375 reachable
> [OK  ] 127.0.0.1:2375 reachable
> [OK  ] [::1]:2375 reachable
> [OK  ] 'wsl -d clf_dockerinwsl nslookup one.one.one.one' succeeded
> [OK  ] 'wsl -d clf_dockerinwsl nslookup host.docker.internal' succeeded
> [OK  ] 'wsl -d clf_dockerinwsl nslookup gateway.docker.internal' succeeded
> [OK  ] 'wsl -d clf_dockerinwsl nslookup host.internal' succeeded
> [OK  ] 'wsl -d clf_dockerinwsl nslookup wsl.internal' succeeded
> Unable to find image 'alpine:latest' locally
> latest: Pulling from library/alpine
> f56be85fc22e: Already exists
> Digest: sha256:124c7d2707904eea7431fffe91522a01e5a861a624ee31d03372cc1d138a3126
> Status: Downloaded newer image for alpine:latest
> [OK  ] 'docker run --rm -it alpine nslookup one.one.one.one' succeeded
> [OK  ] 'docker run --rm -it alpine nslookup host.docker.internal' succeeded
> [OK  ] 'docker run --rm -it alpine nslookup gateway.docker.internal' succeeded
> [OK  ] 'docker run --rm -it alpine nslookup host.internal' succeeded
> [OK  ] 'docker run --rm -it alpine nslookup wsl.internal' succeeded
> 
> C:\Users\<>>docker-wsl status
> chrony                           RUNNING   pid 385, uptime 5:34:30
> dnsmasq                          RUNNING   pid 386, uptime 5:34:30
> dockerd                          RUNNING   pid 387, uptime 5:34:30
> mount                            RUNNING   pid 383, uptime 5:34:30
> startup                          RUNNING   pid 382, uptime 5:34:30
> vpnkit                           RUNNING   pid 384, uptime 5:34:30
